spring:
  profiles:
    active: dev
  datasource:
#    url: jdbc:mysql://localhost:3306/tutorial
#    username: root
#    password: admin
    url: jdbc:h2:mem:testdb
    username: root
    password: admin
  sql:
    init:
      mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org.example: DEBUG